<?php

namespace Voiture\ListeBundle\Repository;

/**
 * marqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marqueRepository extends \Doctrine\ORM\EntityRepository
{
}
