<?php

namespace Voiture\ListeBundle\Repository;

/**
 * PiloteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiloteRepository extends \Doctrine\ORM\EntityRepository
{
}
