<?php

namespace Voiture\ListeBundle\Repository;

/**
 * voitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voitureRepository extends \Doctrine\ORM\EntityRepository
{
}
